### ISSUE TITLE
configure: error: GCC 6.2.1 is too old, must be at least GCC 7.0.0

### ISSUE THREAD

**Issue by miclill** [mrkara/libreoffice-build-environment#1]
configure: error: GCC 6.2.1 is too old, must be at least GCC 7.0.0
Error running configure at ./autogen.sh line 296.

I can offer to create a PR to either deprecate the repo or upgrade to debian:testing which contains GCC 8.2. Would one of the options be in your senses (@mrkara )?

**Comment by mrkara** [comment]
> configure: error: GCC 6.2.1 is too old, must be at least GCC 7.0.0
> Error running configure at ./autogen.sh line 296.
> 
> I can offer to create a PR to either deprecate the repo or upgrade to debian:testing which contains GCC 8.2. Would one of the options be in your senses (@mrkara )?

Hi @miclill 

A PR to upgrade would be appreciated. Thank you! :)

Best
